# Paramétrage de l'environnement de travail et import des packages

In [6]:
import sys
from pathlib import Path

In [7]:
ROOT = Path.cwd().parents[0]

RAW_DATA = ROOT / "01_data" / "01_raw"
PROCESSED_DATA = ROOT / "01_data" / "02_processed"

%load_ext autoreload
%autoreload 2
sys.path.append(str(ROOT / "03_fonctions"))

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [8]:
import pandas as pd
from fonctions_perso.geo_localisation import calcul_distances
from cleaning.feature_engineering_and_selection import data_fraud_cleaning

# La base de données initiale

In [24]:
data_fraud = pd.read_parquet(RAW_DATA / "fraud_data.parquet")

**Informations globales**

In [25]:
data_fraud.info() # Pas de valeurs manquantes !

<class 'pandas.core.frame.DataFrame'>
Index: 563225 entries, 0 to 1295733
Data columns (total 23 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Unnamed: 0             563225 non-null  int64
 1   trans_date_trans_time  563225 non-null  object
 2   cc_num                 563225 non-null  int64
 3   merchant               563225 non-null  object
 4   category               563225 non-null  object
 5   amt                    563225 non-null  float64
 6   first                  563225 non-null  object
 7   last                   563225 non-null  object
 8   gender                 563225 non-null  object
 9   street                 563225 non-null  object
 10  city                   563225 non-null  object
 11  state                  563225 non-null  object
 12  zip                    563225 non-null  int64
 13  lat                    563225 non-null  float64
 14  long                   563225 non-null  float64
 15  city_pop               563225 non-null  int64
 16  job                    563225 non-null  object
 17  dob                    563225 non-null  object
 18  trans_num              563225 non-null  object
 19  unix_time              563225 non-null  int64
 20  merch_lat              563225 non-null  float64
 21  merch_long             563225 non-null  float64
 22  is_fraud               563225 non-null  int64
dtypes: float64(5), int64(6), object(12)
memory usage: 103.1+ MB

**Statistiques descriptives**

In [26]:
data_fraud.describe()

,Unnamed: 0,cc_num,amt,zip,lat,long,city_pop,unix_time,merch_lat,merch_long,is_fraud
count,5.632250e+05,5.632250e+05,563225.000000,563225.000000,563225.000000,563225.000000,5.632250e+05,5.632250e+05,563225.000000,563225.000000,563225.000000
mean,2.824846e+05,4.176057e+17,75.548833,48831.914398,38.544857,-90.227123,8.834256e+04,1.380249e+09,38.544278,-90.227175,0.017135
std,1.706452e+05,1.309403e+18,170.529091,26860.925816,5.062845,13.729378,3.007564e+05,6.553585e+06,5.097493,13.740796,0.129775
min,0.000000e+00,6.041621e+10,1.000000,1257.000000,20.027100,-165.672300,2.300000e+01,1.325466e+09,19.027422,-166.671575,0.000000
25%,1.394970e+05,1.800429e+14,9.730000,26237.000000,34.690200,-96.798000,7.410000e+02,1.375827e+09,34.760443,-96.901767,0.000000
50%,2.795150e+05,3.521417e+15,47.840000,48174.000000,39.371600,-87.476900,2.408000e+03,1.380581e+09,39.377368,-87.440158,0.000000
75%,4.196860e+05,4.635331e+15,84.440000,72011.000000,41.894800,-80.175200,1.968500e+04,1.385842e+09,41.954514,-80.260118,0.000000
max,1.295733e+06,4.992346e+18,22768.110000,99921.000000,66.693300,-67.950300,2.906700e+06,1.388534e+09,67.510267,-66.952026,1.000000

**Aperçu rapide des données**

In [27]:
data_fraud.head()

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2020-06-21 12:14:25,2291163933867244,fraud_Kirlin and Sons,personal_care,2.86,Jeff,Elliott,M,351 Darlene Green,...,33.9659,-80.9355,333497,Mechanical engineer,1968-03-19,2da90c7d74bd46a0caf3777415b3ebd3,1371816865,33.986391,-81.200714,0
1,1,2020-06-21 12:14:33,3573030041201292,fraud_Sporer-Keebler,personal_care,29.84,Joanne,Williams,F,3638 Marsh Union,...,40.3207,-110.4360,302,"Sales professional, IT",1990-01-17,324cc204407e99f51b0d6ca0055005e7,1371816873,39.450498,-109.960431,0
2,2,2020-06-21 12:14:53,3598215285024754,"fraud_Swaniawski, Nitzsche and Welch",health_fitness,41.28,Ashley,Lopez,F,9333 Valentine Point,...,40.6729,-73.5365,34496,"Librarian, public",1970-10-21,c81755dbbbea9d5c77f094348a7579be,1371816893,40.495810,-74.196111,0
3,3,2020-06-21 12:15:15,3591919803438423,fraud_Haley Group,misc_pos,60.05,Brian,Williams,M,32941 Krystal Mill Apt. 552,...,28.5697,-80.8191,54767,Set designer,1987-07-25,2159175b9efe66dc301f149d3d5abf8c,1371816915,28.812398,-80.883061,0
4,4,2020-06-21 12:15:17,3526826139003047,fraud_Johnston-Casper,travel,3.19,Nathan,Massey,M,5783 Evan Roads Apt. 465,...,44.2529,-85.0170,1126,Furniture designer,1955-07-06,57ff021bd3f328f8738bb535c302a31b,1371816917,44.959148,-85.884734,0

# Base de données après transformations

In [28]:
data_fraud = data_fraud_cleaning()

Import des données et modification des types : OK
==================================================
Renommage des variables : OK
==================================================
Nettoyage de la variable 'nom_magasin' : OK
==================================================
Création des nouvelles variables : OK
==================================================
Suppressions des variables non utilisables : OK
==================================================
✅ Datasource 'data_fraud' prête.
📸 Asset 'cleaning_engineering_selection' mis à jour.

Calculating Metrics:   0%|          | 0/3 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/2 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/6 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/7 [00:00<?, ?it/s]

Règle 1 (expect_table_column_count_to_equal): OK
Règle 2 (expect_column_to_exist): OK
Règle 3 (expect_column_values_to_not_be_null): OK
Les conditions sont validés, export possible
Export des données : OK
==================================================

**Informations globales**

In [29]:
data_fraud.info()

<class 'pandas.core.frame.DataFrame'>
Index: 563225 entries, 0 to 1295733
Data columns (total 19 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   nom_magasin                563225 non-null  object
 1   type_magasin               563225 non-null  object
 2   montant_transaction        563225 non-null  float64
 3   ville_client               563225 non-null  object
 4   etat_client                563225 non-null  object
 5   latitude_domicile_client   563225 non-null  float64
 6   longitude_domicile_client  563225 non-null  float64
 7   population_ville_client    563225 non-null  int64
 8   profession_client          563225 non-null  object
 9   numero_transaction         563225 non-null  object
 10  latitude_magasin           563225 non-null  float64
 11  longitude_magasin          563225 non-null  float64
 12  target                     563225 non-null  int64
 13  annee_transaction          563225 non-null  int32
 14  mois_transaction           563225 non-null  object
 15  jour_transaction           563225 non-null  object
 16  heure_transaction          563225 non-null  int32
 17  distance_domicile_magasin  563225 non-null  float64
 18  age_client                 563225 non-null  int32
dtypes: float64(6), int32(3), int64(2), object(8)
memory usage: 79.5+ MB

**Statistiques descriptives**

In [30]:
data_fraud.describe()

,montant_transaction,latitude_domicile_client,longitude_domicile_client,population_ville_client,latitude_magasin,longitude_magasin,target,annee_transaction,heure_transaction,distance_domicile_magasin,age_client
count,563225.000000,563225.000000,563225.000000,5.632250e+05,563225.000000,563225.000000,563225.000000,563225.000000,563225.000000,563225.000000,563225.000000
mean,75.548833,38.544857,-90.227123,8.834256e+04,38.544278,-90.227175,0.017135,2019.990732,12.825437,76.107185,46.665956
std,170.529091,5.062845,13.729378,3.007564e+05,5.097493,13.740796,0.129775,0.095824,6.858912,29.112272,17.440321
min,1.000000,20.027100,-165.672300,2.300000e+01,19.027422,-166.671575,0.000000,2019.000000,0.000000,0.123883,14.000000
25%,9.730000,34.690200,-96.798000,7.410000e+02,34.760443,-96.901767,0.000000,2020.000000,7.000000,55.292554,33.000000
50%,47.840000,39.371600,-87.476900,2.408000e+03,39.377368,-87.440158,0.000000,2020.000000,14.000000,78.178017,45.000000
75%,84.440000,41.894800,-80.175200,1.968500e+04,41.954514,-80.260118,0.000000,2020.000000,19.000000,98.518288,58.000000
max,22768.110000,66.693300,-67.950300,2.906700e+06,67.510267,-66.952026,1.000000,2020.000000,23.000000,150.922713,96.000000

**Apercu rapide des données**

In [31]:
data_fraud.head()

,nom_magasin,type_magasin,montant_transaction,ville_client,etat_client,latitude_domicile_client,longitude_domicile_client,population_ville_client,profession_client,numero_transaction,latitude_magasin,longitude_magasin,target,annee_transaction,mois_transaction,jour_transaction,heure_transaction,distance_domicile_magasin,age_client
0,Kirlin and Sons,personal_care,2.86,Columbia,SC,33.9659,-80.9355,333497,Mechanical engineer,2da90c7d74bd46a0caf3777415b3ebd3,33.986391,-81.200714,0,2020,June,Sunday,12,24.561496,52
1,Sporer-Keebler,personal_care,29.84,Altonah,UT,40.3207,-110.4360,302,"Sales professional, IT",324cc204407e99f51b0d6ca0055005e7,39.450498,-109.960431,0,2020,June,Sunday,12,104.925237,30
2,"Swaniawski, Nitzsche and Welch",health_fitness,41.28,Bellmore,NY,40.6729,-73.5365,34496,"Librarian, public",c81755dbbbea9d5c77f094348a7579be,40.495810,-74.196111,0,2020,June,Sunday,12,59.080159,50
3,Haley Group,misc_pos,60.05,Titusville,FL,28.5697,-80.8191,54767,Set designer,2159175b9efe66dc301f149d3d5abf8c,28.812398,-80.883061,0,2020,June,Sunday,12,27.698606,33
4,Johnston-Casper,travel,3.19,Falmouth,MI,44.2529,-85.0170,1126,Furniture designer,57ff021bd3f328f8738bb535c302a31b,44.959148,-85.884734,0,2020,June,Sunday,12,104.335250,65

# Note explicative du Notebook

Ce notebook met en place la première étape du projet : préparer les données de transactions avant l’analyse exploratoire et la modélisation.

### 1. Import et remise en forme

Les données sont chargées depuis un fichier parquet puis certains types sont corrigés (dates, identifiants en `object`, etc.).  
Les variables sont ensuite renommées pour obtenir des noms clairs et orientés métier (ex. `amt` → `montant_transaction`, `is_fraud` → `target`).

### 2. Nettoyage

- Nettoyage du champ `nom_magasin`.
- Suppression des variables non exploitables ou sensibles :
  - identifiants directs (`numero_carte`, `prenom`, `nom`)
  - variables posant des enjeux éthiques (`sexe`)
  - informations redondantes ou trop fines (`adresse_client`, `code_postal_client`, `timestamp_unix_transacation`, etc.)

L’objectif est de conserver uniquement des variables pertinentes pour la détection de fraude.

### 3. Création de variables (feature engineering)

Ajout de variables dérivées pour enrichir l’information :

- **Variables temporelles** : année, mois, jour, heure de transaction  
- **Distance domicile–magasin** : calculée à partir des coordonnées GPS  
- **Âge du client** : dérivé de la date de naissance

Ces variables visent à capturer :
- des comportements inhabituels dans le temps (heures atypiques, saisonnalité),
- des incohérences géographiques,
- des effets liés au profil du client.

### 4. Contrôle qualité et export

Un contrôle qualité est réalisé avec Great Expectations :
- vérification du nombre de colonnes,
- présence de la variable cible,
- absence de valeurs nulles sur `target`.

Si les conditions sont validées, la table nettoyée est exportée en parquet (`data_fraud_processed.parquet`) pour l’EDA et la suite du pipeline

---

En résumé, ce notebook transforme les données brutes issues du dataset Kaggle en une table propre, enrichie et prête pour l’analyse exploratoire et la modélisation.